name:                boggler
version:             0.1.0.0
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2018 Author name here"

dependencies:
- base >= 4.7 && < 5
- bytestring-trie
- bytestring
- containers
- recursion-schemes
- criterion
- deepseq
- deepseq-generics
- generic-deriving
- random
- timeit
- time

library:
  source-dirs: src

executables:
  boggler:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - boggler
